### ISSUE TITLE
Create a Postfix container image

### ISSUE THREAD

**Issue by dcermak** [SUSE/BCI-dockerfile-generator#1021]
The container image should contain the Postfix MTA with a suitable entrypoint to launch auto-launch postfix if supplied with no commands. Configuration can be performed via environment variables or via mounting/copying the configuration files.

The image **must** have a decent README explaining the various configuration options and preferably also usage examples.

Potential inspiration:
- https://hub.docker.com/r/tozd/postfix (source: https://gitlab.com/tozd/docker/postfix)
- registry.opensuse.org/opensuse/postfix (source: https://github.com/thkukuk/containers-mailserver/tree/master/postfix)

**Comment by dirkmueller** [comment]
postfix container is created.
