### ISSUE TITLE
Create a apache container image

### ISSUE THREAD

**Issue by dcermak** [SUSE/BCI-dockerfile-generator#1022]

**Comment by alexandrevicenzi** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Create Apache image](https://trello.com/c/fYfES3gQ/7-create-apache-image)

**Comment by dirkmueller** [comment]
what is the purpose of the image? serve static files?

**Comment by alexandrevicenzi** [comment]
@dirkmueller Apache alone is just a static file server. The image needs to be extended anytime someone wants to use something extra, for example, to include PHP/FPM or mod WSGI.

@dcermak can you clarify the image requirements? Should the image be called httpd or apache2?

**Comment by dirkmueller** [comment]
@alexandrevicenzi exactly, who uses apache for serving static files? so is it a development container then only?

**Comment by alexandrevicenzi** [comment]
@dirkmueller I honestly don't know, the request for this image is vague. I created an image PR which includes Apache httpd only, PHP/FPM/Apache is already available in the PHP images.

**Comment by alexandrevicenzi** [comment]
@dirkmueller as you saw today, we agreed that this container image is not needed. We currently have the PHP-Apache that can be used for the LAMP stack.
