### ISSUE TITLE
mariadb entrypoint.sh / healthcheck.sh

### ISSUE THREAD

**Issue by grooverdan** [SUSE/BCI-dockerfile-generator#1207]
@dcermak,

note per https://github.com/MariaDB/mariadb-docker/commit/44ed2e231207787c08d56acc94b79d5f06efe006

%%MARIADB_VERSION_BASIC%% needs to be populated with the version of the release.
https://build.opensuse.org/package/rdiff/openSUSE:Factory/mariadb-image?linkrev=base&rev=13 wasn't sufficient.

note also healthcheck.sh substitutions

https://github.com/MariaDB/mariadb-docker/blob/44ed2e231207787c08d56acc94b79d5f06efe006/update.sh#L103
https://github.com/MariaDB/mariadb-docker/blob/44ed2e231207787c08d56acc94b79d5f06efe006/update.sh#L114

with 10.4 having its last release, yes I need to cleanup the update.sh script more.

If complete Docker Official Images compatibility is a goal running
https://github.com/MariaDB/mariadb-docker/blob/master/.test/run.sh (with the other files in .test cloned) with the container image as the argument will run tests.

Some components of https://github.com/MariaDB/mariadb-docker/blob/master/docker.cnf might be required for compatibility along with `jemalloc` installation.

**Comment by grooverdan** [comment]
note when you have the image compatibility, you also have https://github.com/mariadb-operator/mariadb-operator compatibility.

**Comment by dirkmueller** [comment]
@grooverdan hey, thanks for these pointers and the hints on what to improve. we'll take a look at that shortly. jfyi, we have another testsuite here: https://github.com/SUSE/BCI-tests/blob/main/tests/test_mariadb.py . I'll see if we can combine them somehow.

**Comment by grooverdan** [comment]
Nice looking test suite. Well done. I'm slightly embarrassed about my shell scripts now :smile:. Yes, I'm happy for a joint collaboration and have enough basic python skills to get by.

So it looks like my hacky script might be good a somewhat reference for things to add to a test suite.

Given for me to use the BCI-tests I'd need to fetch the `test_mariadb.py`, fake the `bci_tester.data` as a `ParameterSet` and otherwise have the same python dependencies.

Other less hacky ways of integration welcome.

Have you come across https://github.com/testcontainers/testcontainers-python/blob/main/modules/mysql/testcontainers/mysql/__init__.py ? There's a [Java module](https://github.com/testcontainers/testcontainers-java/blob/main/modules/mariadb/src/main/java/org/testcontainers/containers/MariaDBContainer.java) for MariaDB but not a Python one (yet). Does seem more user focused however. `pytest_container` does seem to contain all you need though.

**Comment by grooverdan** [comment]
FYI updated (https://github.com/MariaDB/mariadb-docker/commit/aecdf2e61356f7ecf31a171e4eed180b7021570a) but not in master branch yet.

Looks like the `update-files.sh` script pulling per version as going to work fine.

As you're consuming scripts, if you have spare cycles to monitor and review changes that would be much appreciated: https://github.com/MariaDB/mariadb-docker/pull/595
