### ISSUE TITLE
Enhancement of BCI-golang* Description

### ISSUE THREAD

**Issue by vmoutoussamy** [SUSE/BCI-dockerfile-generator#1248]
The [Rancher Security Team](https://confluence.suse.com/display/RST)  have noticed the following note in https://registry.suse.com/repositories/bci-golang121

> Note: The Golang image should be used as a build environment. For runtime, self-contained Go binaries should use a scratch image and for applications that require external dependencies use the bci-base image.

We believe that this note is important and might be better placed in the description of the image itself for better exposure, making it less likely that someone will miss this description and recommendation as it will be at the top of the image page.

**Comment by alexandrevicenzi** [comment]
I'm inclined to say that people are more likely to miss it in the description. Right below the podman command you are about to copy and paste is easier to spot.

@dmpop do you know which place is ideal for this kind of information?

**Comment by dirkmueller** [comment]
this information has been included in the golang READMEs meanwhile.
