### ISSUE TITLE
postfix image has several command not found errors including syslogd

### ISSUE THREAD

**Issue by thkukuk** [SUSE/BCI-dockerfile-generator#1545]
The `/entrypoint/entrypoint.sh: line 411: /usr/sbin/syslogd: No such file or directory error` of the postfix container is annoying.  Like `/usr/lib/postfix/bin//postfix-script: line 400: cmp: command not found`.

For the former one, https://github.com/thkukuk/containers-mailserver/commit/11d144f9fa673fada91786f5d457f17189bdacc8 needs to be ported. Should apply fine on the normal entrypoint.sh file, but I have no clue about the changes done for entrypoint.sles.sh. And of course Dockerfile needs to be adjusted.
For the second one, our postfix maintainers just need to accept the SR with the fix for the package...

**Comment by dirkmueller** [comment]
I believe this is meanwhile fixed (tests are passing at least..)
