### ISSUE TITLE
Addition of test cases

### ISSUE THREAD

**Issue by ilyas829** [SUSE/BCI-dockerfile-generator#1798]
- Positive as well as negative test cases are important to handle breakage of code at users perspective
- I have added few test cases (pytest test function ) to handle few Issues.
- please review my PR and merge it

1.  https://github.com/SUSE/BCI-dockerfile-generator/pull/1797
2. https://github.com/SUSE/BCI-dockerfile-generator/pull/1796
3. https://github.com/SUSE/BCI-dockerfile-generator/pull/1795
4. https://github.com/SUSE/BCI-dockerfile-generator/pull/1794

If more test should be added please give your suggestions or feedback @dirkmueller .

**Comment by alexandrevicenzi** [comment]
There's no need to create an issue for open PRs, we can see that PRs are open.
