### ISSUE TITLE
replace gosu "script" in mariadb containers with real gosu or at least a fully compatible wrapper

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/BCI-dockerfile-generator#2070]
from https://github.com/SUSE/BCI-dockerfile-generator/pull/963/files#r1859152125

we should either switch to https://github.com/tianon/gosu/blob/3c1fd16340edbc0e984ba4674379da23ebb82abf/setpriv-wrapper.sh or simply give our shell script (which is similar but not the same) a different name to avoid confusion.

**Comment by alexandrevicenzi** [comment]
Which option is better @dirkmueller @dcermak?

I think renaming the script is the simplest solution, not sure if we need `gosu`, maybe it would be useful, but so far no one asked for a proper `gosu`.

**Comment by dirkmueller** [comment]
I would go with renaming.

**Comment by dcermak** [comment]
> Which option is better @dirkmueller @dcermak?
> 
> I think renaming the script is the simplest solution, not sure if we need `gosu`, maybe it would be useful, but so far no one asked for a proper `gosu`.

I'd go for renaming as well. IMHO we don't need to add gosu to a code stream nearing the end of its development period
