### ISSUE TITLE
`org.opencontainers.image.source` url missing for OCI sbom/changelog tracking

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/BCI-dockerfile-generator#252]
should we point to https://github.com/SUSE/BCI-dockerfile-generator/tree/15-sp$sp/$package-image ?

there are tools that expect this label to find the sources the image was built from

**Comment by dcermak** [comment]
There would be a certain duplication with `org.openbuildservice.disturl` and the actual source is on IBS/OBS. The contents should be the same though, so I guess adding it won't really hurt.

**Comment by Vogtinator** [comment]
Any reason you don't use `%SOURCEURL%`?
