### ISSUE TITLE
SP5 is now Goldmaster - flip labels to released

### ISSUE THREAD

**Issue by msmeissn** [SUSE/BCI-dockerfile-generator#431]
With SLES 15 SP5 now being declared Goldmaster, the containerr labels can be flipped to "released"

**Comment by msmeissn** [comment]
to be clear, we currently ship micro, minimal, init and busybox for 15-sp5 already... I think they could switch to released, but not sure if now. We might need to ask the releasemgr

We currently do NOT ship the other language+app containers, this waits until FCS (end of JUne), but there we can already change the labels to have them ready for delivery.

**Comment by dirkmueller** [comment]
@msmeissn any success in asking release mgmt?

**Comment by msmeissn** [comment]
Vincent wants to discuss it on Tuesday sync call. I put it on the agenda.
