### ISSUE TITLE
10-listen-on-ipv6-by-default.sh not working in nginx/rmt-nginx image

### ISSUE THREAD

**Issue by dirkmueller** [SUSE/BCI-dockerfile-generator#547]
the errors on start are:

```
10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/nginx.conf
10-listen-on-ipv6-by-default.sh: info: Unsupported distribution
```

and this is after fixing the default config location in the script which is already wrong.

**Comment by dcermak** [comment]
@brunoleon This needs to be reported upstream, as the file in question is pulled from the nginx image from dockerhub

**Comment by brunoleon** [comment]
The script is looking for the distribution ID and Suse is not one of the supported one so I'm not sure this is to be reported upstream, or it would mean to add support for another distribution.
