### ISSUE TITLE
Mariadb entrypoint needs refreshing & fixes for MARIADB_RANDOM_ROOT_PASSWORD

### ISSUE THREAD

**Issue by dcermak** [SUSE/BCI-dockerfile-generator#794]
- [ ] the file `src/bci_build/package/mariadb/entrypoint.sh` is an outdated copy of https://github.com/MariaDB/mariadb-docker/blob/master/docker-entrypoint.sh, we should update it automatically
- [ ] the env var `MARIADB_RANDOM_ROOT_PASSWORD` will not work in SLES, because we don't have `pwqgen` in SLE

**Comment by dirkmueller** [comment]
the pwgen is now replaced with openssl rand -base64 so it works with SLE. I'll extend test coverage for that.

**Comment by dirkmueller** [comment]
tested via https://github.com/SUSE/BCI-tests/pull/480
