### ISSUE TITLE
ASP.NET base image is missing ASPNETCORE_URLS

### ISSUE THREAD

**Issue by devpro** [SUSE/BCI-dockerfile-generator#887]
## Reproduction steps

* Create an ASP.NET project from the official template (with `dotnet new webapi ...` for example)
* Edit the `Dockerfile` to use SUSE BCI
* Build the image
* Run a container

See the example: [devpro/container-images/samples/dotnet/8.0](https://github.com/devpro/container-images/tree/main/samples/dotnet/8.0)

## Expected behavior

Clicking on the URL will open the Swagger page.

## Actual behavior

Page 404 is displayed.

## Workaround

Add ASPNETCORE_URLS environment variable (`ASPNETCORE_URLS=http://[::]:8080` for example)

## Impact

It may impact the user adoption while migrating to SUSE BCI as there is an extra step (undocumented) compared with the default/official images from Microsoft.

**Comment by dirkmueller** [comment]
according to the MS image and https://learn.microsoft.com/en-us/dotnet/core/compatibility/containers/8.0/aspnet-port we can use ASPNETCORE_HTTP_PORTS=8080 which is also what the image is doing. 

I'm still not able to get your example to work though

**Comment by devpro** [comment]
@dirkmueller here is a video where I reproduce the issue: [youtube.com/watch?v=4U0yZM9qEZg](https://www.youtube.com/watch?v=4U0yZM9qEZg)

I do it from scratch, with a git clone in an empty dir, then follow the README. (the code in this sample is the one generated by the template, I just make few minors changes to follow .NET conventions)

_TL;DR_ With BCI I need to add an environment variable ASPNETCORE_URLS to make the web app work (not needed with Microsoft image)
