### ISSUE TITLE
Add proper README to images

### ISSUE THREAD

**Issue by alexandrevicenzi** [SUSE/BCI-dockerfile-generator#993]
Most images currently have a rather small incomplete README or none at all.

Adding a proper README to our images will help users deploy applications quickly.

Containers missing a README:

- [x] MariaDB Server (#1024)
- [x] MariaDB Client (#1342)
- [x] PostgreSQL (#1118)
- [x] 389 Directory Server (#1299)
- [x] Nginx (#1126)
- [x] Git (#2049)
- [x] Helm (#1276)
- [x] Go (#1169)
- [x] OpenJDK (#1344)
- [x] Python (#1195)
- [x] NodeJS (#1241)
- [x] .NET (#1420)
- [x] Rust (#1236)
- [x] Ruby (#1238)
- [x] PHP (#1156)
- [x] Kernel Module (#1542)
- [x] RMT (#1141)

**Comment by alexandrevicenzi** [comment]
MariaDB Server is done.
PostgreSQL is up for review.
Starting to work on Nginx.

**Comment by Priyankasaggu11929** [comment]
I'll work on adding README for Helm.

**Comment by dcermak** [comment]
I'll take PHP

**Comment by alexandrevicenzi** [comment]
I'll take Go.

**Comment by dcermak** [comment]
I'll take the kernel module container

**Comment by alexandrevicenzi** [comment]
I'll take Python.

**Comment by alexandrevicenzi** [comment]
I'll take Rust.

**Comment by alexandrevicenzi** [comment]
I'll take Ruby.

**Comment by alexandrevicenzi** [comment]
I'll take NodeJS.

**Comment by alexandrevicenzi** [comment]
I'll take 389 DS.

**Comment by alexandrevicenzi** [comment]
I'll take Git.

**Comment by alexandrevicenzi** [comment]
I'll take OpenJDK.

**Comment by alexandrevicenzi** [comment]
I'll take .NET.
